image: node:latest

stages:
  - build
  - test

build_front_end:
  stage: build
  script:
    - cd front-end
    - npm install
    - CI=false npm run-script build

front_end_unit_test:
  stage: test
  script:
    - cd front-end
    - npm install
    - CI=true npm test
